### PR TITLE
[FTR] Add option to hide dataset by default and give pie charts a specific color per group

### PR DESCRIPTION
**Pull request by ITMobilityControl**
Adds the option to hide a dataset by default. Can be useful when you have multiple datasets in one chart and want to show only one of them when loading the page.

### CODE REVIEW

**Comment by ITMobilityControl** [comment]
The latest commit also adds the option to give pie charts a specific color per group.
image
image

**Comment by PovilasKorop** [comment]
@ITMobilityControl thank you for the contribution, merged and released a new version

**Comment by ITMobilityControl** [comment]
@PovilasKorop It's the least I can do after all of your tutorials and the super useful quickadminpanel website! :)

**Review by Williamug — COMMENTED** [review]
:+1:

**Pull request merged**
