### PR TITLE
Pull request

### PR DESCRIPTION
**Pull request by neppoz**
Added two lines of documentation and a new option to specify the chart_height

### CODE REVIEW

**Comment by PovilasKorop** [comment]
@neppoz why specifically 150 height? It may be quite small on bigger resolutions, don't you think? And I'm not sure I want to specify the default height, I think if it's not provided as a parameter then it should not appear in HTML. Can you change?

**Comment by neppoz** [comment]
> @neppoz why specifically 150 height? It may be quite small on bigger resolutions, don't you think? And I'm not sure I want to specify the default height, I think if it's not provided as a parameter then it should not appear in HTML. Can you change?

Good point, i removed the default value of 150 to '', so if you don't set the parameter it will not limit to specific height

**Comment by PovilasKorop** [comment]
@neppoz still not perfect, sorry, I meant that `height` HTML attribute should be removed at all when not specified. Cause I'm not sure how various browsers would treat `height=""`

**Comment by PovilasKorop** [comment]
@neppoz sorry again but you mixed a few things in the same PR so I can't accept until ALL is done. I disagree with this one: https://github.com/LaravelDaily/laravel-charts/pull/33/commits/0e9d8562ca2a031877f79d1a25663c456dbd1a30

For our specific purposes, we prefer to make them publishable, for reusing in our QuickAdminPanel, to avoid extra artisan command for our customers.

**Comment by PovilasKorop** [comment]
@neppoz I'm sure you didn't have time for this, update from my side: I've changed that one line in the Readme, and your other changes I just can't accept as a Pull Request, sorry.

**Pull request closed without merging**
